### ISSUE TITLE
Sniproxy

### ISSUE THREAD

**Issue by marcusboon** [noxtech/gamecache-docker-compose#1]
Just a quick question, how do you confirm that SNIProxy is indeed using the macvlan and capturing all HTTPS traffic for each of the cache containers? I have a similar setup where I've segregated the containers into their own IP addresses, and steam video/pictures don't seem to be loading properly all of the time.

**Comment by matthewhaywardmsm** [comment]
Since Origin only uses HTTPS for it's caching, you could see if it's successfully caching Origin games. There's probably a more intelligent way to do it though...

I don't know if the videos / pictures are served from the same CDNs used by the game install files themselves. Try taking a look at the traffic and the URLs queried when loading a Steam page, e.g. using [Charles Proxy](https://www.charlesproxy.com/).

**Comment by matthewh86** [comment]
Since Origin only uses HTTPS for it's caching, you could see if it's successfully caching Origin games. There's probably a more intelligent way to do it though...

I don't know if the videos / pictures are served from the same CDNs used by the game install files themselves. Try taking a look at the traffic and the URLs queried when loading a Steam page, e.g. using Charles Proxy.

**Comment by marcusboon** [comment]
I gave up with the docker containers. It was much easier to just setup nginx as a reverse proxy and do it locally. Harder to setup but at least its working much more reliably now.

**Comment by matthewh86** [comment]
You could try using the docker-compose file at
https://github.com/steamcache/docker-compose

This is working for me atm, the only drawback is that it isn't bound to a
specific interface which using macvlan gives.
